use_frameworks!(linkage: :static)

platform :ios, '13.0'

target 'FLEXample' do
  project 'FLEXample-SQLCipher'
  pod 'FLEX', :path => '../../'
  pod 'SQLCipher'
end

post_install do |installer|
  update_pods_targets_settings(installer.pods_project)
end

def update_pods_targets_settings(pods_project)
  pods_project.targets.each do |pod_target|
    pod_target.build_configurations.each do |build_configuration|
      update_pods_target_settings(build_configuration, pod_target.name)
    end
  end
end

def update_pods_target_settings(build_configuration, pod_target_name)
  build_settings = build_configuration.build_settings

  if pod_target_name == 'FLEX'
    build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'SQLITE_HAS_CODEC=1']
    build_settings['HEADER_SEARCH_PATHS'] ||= ['$(inherited)', '${PODS_ROOT}/Headers/Public/SQLCipher']
  end
end
